### ISSUE TITLE
Bugfix: Show notification to user if he tries to upload file already in dropbox

### ISSUE THREAD

**Issue by LiisiMotsharg** [marinanekrassova/smartsafe#80]
Dropbox does not allow adding multiple files with the same name - right now our app swallows this error. 

Make it appear again and show user appropriate notification

**Comment by marinan87** [comment]
Fixed. 

A note for reviewer: You might want to adapt JS code if it looks too ugly. Also, you might find some more appropriate way to display the warning message to user (please let me know if so). 

Otherwise, should be functionally correct.

**Comment by LiisiMotsharg** [comment]
Made some minor fixes to take better advantage of ES6 features. 

Showing alert is perfectly valid way to show warning to user. Reducer function might not be the best place for showing alert, since it's generally meant to be 'pure JS function', that only modifies state and has no sideeffects. 
However, at the moment I cannot think of a better place either.
